# Generated by Django 5.1.2 on 2024-11-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Sceince'), ('C', 'Comerce'), ('A', 'Arts')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
                ('section', models.CharField(blank=True, max_length=30, null=True)),
                ('batch', models.IntegerField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
        ),
    ]
